dist: trusty
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script: sbt ++$TRAVIS_SCALA_VERSION test
deploy:
- provider: script
  script: travis/deploy.sh
  on:
    all_branches: true
if: tag IS blank
